apiVersion: v1
kind: Service
metadata:
  name: pgmaster
spec:
  clusterIP: None  # Headless service for stable DNS
  selector:
    app: postgres
    role: master
  ports:
    - port: 5432
      targetPort: 5432