apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-master-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/pgsql/kube/master"  # Ensure this directory exists on the node